name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: education
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Node.js
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: 20

          
      - name: Restore
        run: dotnet restore ./education.sln
        
      - name: Build
        run: dotnet build  ./education.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish  ./education.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
#      - name: Deployment
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
